[package]
name = "wt-cli"
version = "0.2.0"
authors = ["Liam Scalzulli <liam@scalzulli.com>"]
categories = ["command-line-utilities"]
description = "A simple git worktree manager"
edition = "2024"
homepage = "https://github.com/terror/wt"
license = "CC0-1.0"
repository = "https://github.com/terror/wt"

[[bin]]
name = "wt"
path = "src/main.rs"

[lints.clippy]
all = { level = "deny", priority = -1 }
arbitrary-source-item-ordering = "deny"
pedantic = { level = "deny", priority = -1 }
wildcard_imports = "allow"

[lints.rust]
unreachable_pub = "deny"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.57", features = ["derive"] }

[target.'cfg(unix)'.dependencies]
ratatui = { version = "0.30.0", default-features = false }
skim = { version = "2.0.2", default-features = false, features = ["cli"] }

[dev-dependencies]
indoc = "2.0.7"
pretty_assertions = "1.4.1"
regex = "1.12.3"
tempfile = "3.24.0"
